### ISSUE TITLE
Cannot Compile on macOS 10.12.04

### ISSUE THREAD

**Issue by sean-smith** [ewxrjk/with-readline#6]
I'm getting a couple of errors. Any advice on how to fix this is appreciated!

```
with-readline.c:59:11: error: use of undeclared identifier 'rl_gnu_readline_p'
          rl_gnu_readline_p ? "GNU" : "non-GNU",
with-readline.c:379:5: error: use of undeclared identifier 'rl_catch_signals'
    rl_catch_signals = 0;
    ^
with-readline.c:380:5: error: use of undeclared identifier 'rl_catch_sigwinch'
    rl_catch_sigwinch = 0;
with-readline.c:465:22: error: use of undeclared identifier 'rl_mark'
          rl_point = rl_mark = rl_end = 0;
```

**Comment by ewxrjk** [comment]
L34 of the README

**Comment by slimcatarch** [comment]
If you still encounter this issue even after force link readline, I change the flag to be:

### ./configure LDFLAGS="-L/usr/local/opt/readline/lib" CPPFLAGS="-I/usr/local/opt/readline/include"

After the flags set, make and make install is smooth and I'm happy using sftp now.

Thanks for this great work!
